fix: cause a deployment failure

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -34,6 +34,10 @@ jobs:
           --health-retries=3
 
     steps:
+      - name: Fail Deployment
+        run: |
+          echo "Deployment failed. Exiting with error."
+          exit 1
       # 1. Checkout code
       - name: Checkout code
         uses: actions/checkout@v4
@@ -154,7 +158,3 @@ jobs:
               title: issueTitle,
               body: issueBody,
             });
-      - name: Fail Deployment
-        run: |
-          echo "Deployment failed. Exiting with error."
-          exit 1
