fix: finishing testing rollback

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -122,7 +122,7 @@ jobs:
       #     api_key: ${{ secrets.RENDER_API_KEY }}
       #     github_token: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Force failure (test rollback) # make pipeline fial intentionallt for rollback testing
-        run: |
-          echo "This is a test failure to trigger rollback"
-          exit 1
+      # - name: Force failure (test rollback) # make pipeline fial intentionallt for rollback testing
+      #   run: |
+      #     echo "This is a test failure to trigger rollback"
+      #     exit 1
